services:
  - type: web
    name: scmtracker
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn SCM TRACKER.wsgi:application"
    plan: free
    branch: main
    autoDeploy: true
