# Generated by Django 5.2.3 on 2025-06-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationstream',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stream_logos/'),
        ),
    ]
