# Generated by Django 5.2.3 on 2025-06-15 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmtracker', '0002_moderationstream_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation_date', models.DateTimeField(auto_now_add=True, verbose_name='Moderation Date')),
                ('agent_name', models.CharField(max_length=255, verbose_name='Agent Name (Full Name)')),
                ('curalate_image_id', models.CharField(max_length=100, verbose_name='Curalate Image ID')),
                ('curalate_post_id', models.CharField(max_length=100, verbose_name='Curalate Post ID')),
                ('agent_action', models.CharField(choices=[('approved', 'Approved'), ('approved-Instagram Admin Rights Required', 'Approved-Instagram Admin Rights Required'), ('rejected', 'Rejected')], max_length=50, verbose_name='Agent Action')),
                ('selected_labels', models.JSONField(default=list, verbose_name='Selected Labels for the Post')),
                ('moderation_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scmtracker.moderationstream', verbose_name='Moderation Stream')),
            ],
        ),
    ]
