# Generated by Django 5.2.3 on 2025-06-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmtracker', '0003_postmoderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmoderation',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='postmoderation',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='postmoderation',
            name='agent_action',
            field=models.CharField(choices=[('approved', 'Approved'), ('approved-Instagram Admin Rights Required', 'Approved-Instagram Admin Rights Required'), ('rejected', 'Rejected')], max_length=50, verbose_name='3. Agent Action'),
        ),
        migrations.AlterField(
            model_name='postmoderation',
            name='curalate_image_id',
            field=models.CharField(max_length=100, verbose_name='1. Curalate Image ID'),
        ),
        migrations.AlterField(
            model_name='postmoderation',
            name='curalate_post_id',
            field=models.CharField(max_length=100, verbose_name='2. Curalate Post ID'),
        ),
    ]
