# Generated by Django 5.2.3 on 2025-06-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmtracker', '0004_postmoderation_end_time_postmoderation_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmoderation',
            name='curalate_image_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='1. Curalate Image ID'),
        ),
        migrations.AlterField(
            model_name='postmoderation',
            name='curalate_post_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='2. Curalate Post ID'),
        ),
    ]
