# Generated by Django 5.2.3 on 2025-06-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmtracker', '0005_alter_postmoderation_curalate_image_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmoderation',
            name='curalate_image_id',
            field=models.CharField(max_length=100, verbose_name='1. Curalate Image ID'),
        ),
        migrations.AlterField(
            model_name='postmoderation',
            name='curalate_post_id',
            field=models.CharField(max_length=100, verbose_name='2. Curalate Post ID'),
        ),
        migrations.AddConstraint(
            model_name='postmoderation',
            constraint=models.UniqueConstraint(fields=('curalate_image_id', 'curalate_post_id'), name='unique_image_and_post_id'),
        ),
    ]
