# Generated by Django 5.2.3 on 2025-06-16 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scmtracker', '0006_alter_postmoderation_curalate_image_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postmoderation',
            name='unique_image_and_post_id',
        ),
    ]
