# Generated by Django 5.1.7 on 2025-06-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmtracker', '0007_remove_postmoderation_unique_image_and_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmoderation',
            name='curalate_image_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='1. Curalate Image ID'),
        ),
    ]
