# Generated by Django 5.1.7 on 2025-06-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmtracker', '0008_alter_postmoderation_curalate_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmoderation',
            name='curalate_image_id',
            field=models.CharField(max_length=100, verbose_name='1. Curalate Image ID'),
        ),
    ]
